#! /bin/bash

# Generates random string from given range of input
SECRET_KEY=$(shuf -zern 50 {A..Z} {0..9} {a..z})

setting_file="recruitr/local_settings.py"

# Creates "local_settings.py" file
create_secret_key() {
    touch $setting_file
    echo "SECRET_KEY = ''" > $setting_file

    # Replaces with random string generated by 'shuf'
    sed -i 's/^SECRET_KEY \?= \?.*/SECRET_KEY = '\'"$SECRET_KEY"\''/' $setting_file 
}


edit_secret_key() {
    if grep -q SECRET_KEY $setting_file; then
        sed -i 's/^SECRET_KEY \?= \?.*/SECRET_KEY = '\'"$SECRET_KEY"\''/' $setting_file     
    else
        echo "SECRET_KEY = ''" >> $setting_file
        sed -i 's/^SECRET_KEY \?= \?.*/SECRET_KEY = '\'"$SECRET_KEY"\''/' $setting_file 
    fi
}


if [ -f $setting_file ]; then
    edit_secret_key
else
    create_secret_key
fi